[package]
name = "profiles"
version = "0.1.0"
edition = "2018"

[dependencies]
anchor-lang = "1.9.0"
solana-program = "1.9.0"
tokio = { version = "1", features = ["full"]}
solana-sdk = "1.9.0"
serde = "1.0"
serde_json = "1.0"
